version: '3.8'

services:
  client:
    image: jonathanleedev/split-client:latest
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ${SERVER_CERT_PATH}:/etc/nginx/server.crt
      - ${SERVER_KEY_PATH}:/etc/nginx/server.key
